# Creates a ServiceMonitor that allows Prometheus to scrape application metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s